- hosts: terraform-ansible
  tasks:
    - name: Instalando o Python3, virtualenv
      apt: 
        pkg:
          - python3
          - virtualenv
        update_cache: yes
      become: yes
    - name: Instalando depedencias com pip (Django e Django rest)
      pip: 
        virtualenv: /home/ubuntu/venv
        name: 
          - django
          - djangorestframework
    - name: Verificando se o projeto ja existe
      stat: 
        path: /home/ubuntu/setup/settings.py
      register: projeto
    - name: Iniciando o projeto
      shell: '. /home/ubuntu/venv/bin/activate; django-admin startproject setup /home/ubuntu/'
      when: not projeto.stat.exists
    - name: Alterando o hosts do settings
      lineinfile: 
        path: /home/ubuntu/setup/settings.py
        regexp: 'ALLOWED_HOSTS'
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes